### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by grindaah** [bbodin/slambench-android#1]
I am getting following error when building on preconfigured system 

```
grindaah@grindaah-XPS-12-9Q23:~/work/slambench-android$ make
./gradlew assembleDebug --stacktrace
Incremental java compilation is an incubating feature.
:app:build /home/grindaah/work/slambench-android/dependencies/OpenNI2
Creating installer for OpenNI 2.2 android
Traceback (most recent call last):
  File "./ReleaseVersion.py", line 116, in <module>
    rc = subprocess.call([ ndkDir + '/ndk-build', '-C', buildDir, '-j1' ])
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 20] Not a directory
:app:build /home/grindaah/work/slambench-android/dependencies/OpenNI2 FAILED
```

It seems that ReleaseVersion.py is temporary generated file, so i can't check why it is happening.
Directory ndk-build does not exist, really, but i assume that it was supposed to be created with same ReleaseVersion.py script
Gradle backtrace ends with:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:build /home/grindaah/work/slambench-android/dependencies/OpenNI2'.
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
```

**Comment by bbodin** [comment]
Thanks to you, this has been patched. 
commit b0d0f413d36108d097c7857b769c4c8736524efc
